name: WARDOGS Gold Price

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  gold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Get gold price
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python gold.py
